### ISSUE TITLE
Take config file path from rosee main config file

### ISSUE THREAD

**Issue by torydebra** [ADVRHumanoids/rosee_gazebo_plugins#4]
Until now, the path for config file of gazebo plugin is found like below:
https://github.com/ADVRHumanoids/rosee_gazebo_plugins/blob/7c005382fada31829683a129c510127a2ea4f593/src/RoseePlugin.cpp#L87-L99

@liesrock, I think it is better to add the path into the main rosee config file (where there are already path for urdf and srdf) and take the path from there (the main rosee config path is on the ros param server anyway). 

Also maybe we should put the rosee plugin config file itself in the config folder of ROSEndEffector package, or we should keep it in this repo?

**Comment by liesrock** [comment]
Thanks for opening this @torydebra, I would do the following: integrate the YAML configs for the gazebo plugins inside the main YAML config in the ROSEndEffector repo (https://github.com/ADVRHumanoids/ROSEndEffector/tree/devel/configs).

We will you this YAML also for the low level configs for real hardware: we will understand in the future if we want to have this modular or in one single YAML.

What do you think?

**Comment by torydebra** [comment]
So, you say to add here:
~~~yaml
ROSEndEffector:
  urdf_path: "urdf/heri_II.urdf"
  srdf_path: "srdf/heri_II.srdf"
~~~

These rows:
~~~yaml
# YAML config file for rosee_plugin control for gazebo. Similar syntax to
# the one used by "official" ros plugin http://gazebosim.org/tutorials/?tut=ros_control
#WARNING: DO NOT USE TAB FOR IDENT YAML FILE: This is not permitted by the YAML spec

heri: #robot name
  #Controller for each joint. type now is only JointPositionControllerfor JointVelocityController
  SFB1__SFP1_1_position_controller:
    type: JointPositionController
    joint_name: SFB1__SFP1_1
    pid: {p: 1, i: 0.1, d: 0.05}

  LFB1__LFP1_1_position_controller:
    type: JointPositionController
    joint_name: LFB1__LFP1_1
    pid: {p: 1, i: 0.1, d: 0.05}

  LFB2__LFP2_1_position_controller:
    type: JointPositionController
    joint_name: LFB2__LFP2_1
    pid: {p: 1, i: 0.1, d: 0.05}
~~~

Instead put in the first file the filepath of the second file, as I suggested.

Your solution sounds better than mine for me! As you said in future we can divide the file if it becomes too long.

**Comment by liesrock** [comment]
Exactly!

**Comment by torydebra** [comment]
Committed and solved !
